use_gpu: True
device: 8
early_stop:
  patience: 100
  improve_indicator_mode: mean
federate:
  mode: standalone
  make_global_eval: True
  client_num: 1
  total_round_num: 2000
  method: global
data:
  root: data/
  type: computers
  splitter: 'louvain'
dataloader:
  type: pyg
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 10
  task: node
train:
  local_update_steps: 4
  optimizer:
    lr: 0.15
    weight_decay: 5e-4
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  metrics: ['acc', 'correct','f1score', 'bac']
