use_gpu: True
device: 0
seed: 0
early_stop:
  patience: 100
  improve_indicator_mode: best
federate:
  make_global_eval: False
  client_num: 3
  total_round_num: 400
  method: 'local'
data:
  root: data/
  type: cora
  splitter: 'louvain'
  local_eval_whole_test_dataset: False
dataloader:
  type: pyg
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
  task: node
train:
  local_update_steps: 4
  optimizer:
    lr: 0.25
    weight_decay: 5e-4
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  freq: 1
  metrics: [ 'acc' ]
  best_res_update_round_wise_key: val_acc
