client_1:
  model:
    type: CNN_fsfl_mnist_2_layer
    fsfl_cnn_layer1_out_channels: 128
    fsfl_cnn_layer2_out_channels: 256
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0
client_2:
  model:
    type: CNN_fsfl_mnist_2_layer
    fsfl_cnn_layer1_out_channels: 512
    fsfl_cnn_layer2_out_channels: 256
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0