use_gpu: True
device: 0
seed: 0
early_stop:
  patience: 50
federate:
  mode: standalone
  method: fedapen
  client_num: 5
  sample_client_rate: 1.0
  total_round_num: 200
  make_global_eval: False
fedapen:
  adaptability_ratio: 0.05
  epoch_for_learn_weight: 1
data:
  root: data/
  type: pubmed
  splitter: 'louvain'
dataloader:
  type: pyg
  batch_size: 1
MHFL:
  task: node
  global_model:
    out_channels: 64
    type: gcn
    hidden: 64
    dropout: 0.5
    warpFC: True
    return_proto: False
    feature_dim: 64
    num_classes: 3
    task: node
model:
  type: gcn
  dropout: 0.5
  out_channels: 3
  return_proto: True
  warpFC: False #important
  feature_dim: 64 #important
train:
  local_update_steps: 4
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.25
    weight_decay: 5e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedapen_node_trainer
grad:
  grad_clip: 5.0
eval:
  freq: 1
  metrics: ['acc','global_model_acc','ensemble_model_acc']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: val_acc
vis_embedding: True