use_gpu: True
device: 0
seed: 0
early_stop:
  patience: 50
federate:
  mode: standalone
  method: fedtgp
  client_num: 3
  sample_client_rate: 1.0
  total_round_num: 200
  make_global_eval: False
FedTGP:
  lam: 0.1 # Consistent with the default setup of FedTGP
  margin_threthold: 100.0 # Consistent with the default setup of FedTGP
  server_epochs: 100 # Consistent with the default setup of FedTGP
  server_batch_size: 10 # Consistent with the default setup of FedTGP
  show_verbose: True
  only_CE_loss: False
  use_similarity_for_inference: False
data:
  root: data/
  type: cora
  splitter: 'louvain'
dataloader:
  type: pyg
  batch_size: 1
MHFL:
  task: node
model:
  type: gcn
  dropout: 0.5
  out_channels: 7
  return_proto: True
  warpFC: True #important
  feature_dim: 64 #important
train:
  local_update_steps: 4
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.25
    weight_decay: 5e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedtgp_node_trainer
grad:
  grad_clip: 5.0
eval:
  freq: 1
  metrics: ['acc','acc_based_on_global_prototype']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: val_acc
vis_embedding: False