use_gpu: True
device: 0
early_stop:
  patience: 50
seed: 0
federate:
  mode: standalone
  method: fedkd
  client_num: 5
  total_round_num: 200
  sample_client_rate: 1.0
  make_global_eval: False
MHFL:
  global_model:
    out_channels: 10
    type: CNN_3layers
    hidden: 256
    filter_channels: [64,64,64]
    dropout: 0.5
    use_bn: True
    return_proto: True
fedkd:
  tmin: 0.95
  tmax: 0.98
  use_SVD: True
data:
  file_path: data/MNIST
  type: 'hfl_mnist'
dataloader:
  batch_size: 256
model:
  dropout: 0.5
  out_channels: 10
  return_proto: True
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.005
    momentum: 0.0
#    weight_decay: 1e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedkd_cv_trainer
grad:
  grad_clip: 10.0
eval:
  freq: 1
  metrics: ['acc']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: test_acc
exp_name: 'FedKD_HFL_MNIST'
result_floder: model_heterogeneity/result/manual