use_gpu: True
device: 0
seed: 0
early_stop:
  patience: 50
federate:
  method: fedkd
  mode: standalone
  client_num: 3
  sample_client_rate: 1.0
  total_round_num: 200
  make_global_eval: False
data:
  root: data/
  type: citeseer
  splitter: 'louvain'
dataloader:
  type: pyg
  batch_size: 1
MHFL:
  task: node
  global_model:
    out_channels: 64
    type: gcn
    hidden: 64
    dropout: 0.5
    warpFC: True
    return_proto: True
    feature_dim: 64
    num_classes: 6
    task: node
model:
  type: gcn
  dropout: 0.5
  hidden: 64
  out_channels: 6
  return_proto: True
  warpFC: True
  feature_dim: 64
  task: node
fedkd:
  tmin: 0.95
  tmax: 0.98
  use_SVD: False
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.01
    weight_decay: 5e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedkd_node_trainer
grad:
  grad_clip: 5.0
eval:
  freq: 1
  metrics: ['acc']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: val_acc