use_gpu: True
device: 0
seed: 0
early_stop:
  patience: 50
federate:
  method: poiv4
  mode: standalone
  client_num: 3
  sample_client_rate: 1.0
  total_round_num: 200
  make_global_eval: False
data:
  root: data/
  type: cora
  splitter: 'louvain'
dataloader:
  type: pyg
  batch_size: 1
MHFL:
  task: node
poi:
  use_knn: False
  temp_idx: 3
model:
  type: gcn
  dropout: 0.5
  hidden: 64
  out_channels: 7
  return_proto: True
  warpFC: True #important
  feature_dim: 64 #important
  task: node
train:
  local_update_steps: 4
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.25
    weight_decay: 5e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: poiv4_trainer
grad:
  grad_clip: 5.0
eval:
  freq: 1
  metrics: ['acc','global_model_acc']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: val_acc
plot_acc_curve: True
show_label_distribution: True